name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:


  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version
        - name: Configure
          run: |
            mkdir build
            cmake -S . -B env.buildDir
        - name: Build
          run: cmake --build build
        - name: testing
          run: ./build/main_test

